{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pactrack-marketing.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pactrack-marketing.labels" . | nindent 4 }}
  annotations:
{{- if .Values.ingress.tls.enabled }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
{{- else }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
{{- end }}
{{- with .Values.ingress.annotations }}
{{ toYaml . | nindent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
{{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
